services:
  app:
    build: .
    container_name: zadanie_4
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: dovolenka
      DB_USERNAME: laravel
      DB_PASSWORD: secret

  db:
    image: mysql:8.0
    container_name: laravel_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dovolenka
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: laravel_pma
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: laravel
      PMA_PASSWORD: secret

volumes:
  db_data: